FROM node:20-alpine
WORKDIR /app

RUN corepack enable && corepack prepare pnpm@latest --activate

# Copy package files
COPY package.json ./

# Install dependencies
RUN pnpm install

EXPOSE 4200
CMD ["pnpm", "dev", "--host", "0.0.0.0"]
