-- Upsert all 125 Moroccan courts from official Excel reference list.
-- Uses standard SQL MERGE (ISO SQL:2003) compatible with H2 2.x and PostgreSQL 15+.

MERGE INTO tribunals AS t
USING (VALUES
('TR_ADM_APPL_1', 'Tribunal d''appel administratif de Rabat', 'محكمة الاستئناف الإدارية بالرباط', TRUE),
('TR_ADM_APPL_2', 'Tribunal d''appel administratif de Marrakech', 'محكمة الإستئناف الإدارية بمراكش', TRUE),
('TR_ADM_PIN_1',  'Tribunal administratif de Rabat', 'المحكمة الإدارية بالرباط', TRUE),
('TR_ADM_PIN_2',  'Tribunal administratif de Casablanca', 'المحكمة الإدارية بالدار البيضاء', TRUE),
('TR_ADM_PIN_3',  'Tribunal administratif de Fes', 'المحكمة الإدارية بفاس', TRUE),
('TR_ADM_PIN_4',  'Tribunal administratif de Meknes', 'المحكمة الإدارية بمكناس', TRUE),
('TR_ADM_PIN_5',  'Tribunal administratif de Oujda', 'المحكمة الإدارية بوجدة', TRUE),
('TR_ADM_PIN_6',  'Tribunal administratif de Marrakech', 'المحكمة الإدارية بمراكش', TRUE),
('TR_ADM_PIN_7',  'Tribunal administratif de Agadir', 'المحكمة الإدارية بأكادير', TRUE),
('TR_COM_APPL_1', 'Tribunal d''appel commercial de Casablanca', 'محكمة الاستئناف التجارية - الدار البيضاء', TRUE),
('TR_COM_APPL_2', 'Tribunal d''appel commercial de Marrakech', 'محكمة الاستئناف التجارية - مراكش', TRUE),
('TR_COM_APPL_3', 'Tribunal d''appel commercial de Fes', 'محكمة الاستئناف التجارية - فاس', TRUE),
('TR_COM_PIN_1',  'Tribunal commercial de Rabat', 'المحكمة التجارية - الرباط', TRUE),
('TR_COM_PIN_2',  'Tribunal commercial de Casablanca', 'المحكمة التجارية - الدار البيضاء', TRUE),
('TR_COM_PIN_3',  'Tribunal commercial de Agadir', 'المحكمة التجارية - أكادير', TRUE),
('TR_COM_PIN_4',  'Tribunal commercial de Marrakech', 'المحكمة التجارية مراكش', TRUE),
('TR_COM_PIN_5',  'Tribunal commercial de Fes', 'المحكمة التجارية بفاس', TRUE),
('TR_COM_PIN_6',  'Tribunal commercial de Meknes', 'المحكمة التجارية بمكناس', TRUE),
('TR_COM_PIN_7',  'Tribunal commercial de Oujda', 'المحكمة التجارية بوجدة', TRUE),
('TR_COM_PIN_8',  'Tribunal commercial de Tanger', 'المحكمة التجارية بطنجة', TRUE),
('TR_APPL_1',  'Tribunal d''appel de Rabat', 'محكمة الاستئناف - بالرباط', TRUE),
('TR_APPL_2',  'Tribunal d''appel de Laayoune', 'محكمة الاستئناف العيون', TRUE),
('TR_APPL_3',  'Tribunal d''appel de Agadir', 'محكمة الاستئناف أكادير', TRUE),
('TR_APPL_4',  'Tribunal d''appel de Ouarzazate', 'محكمة الاستئناف ورزازات', TRUE),
('TR_APPL_5',  'Tribunal d''appel de Kenitra', 'محكمة الاستئناف القنيطرة', TRUE),
('TR_APPL_6',  'Tribunal d''appel de Settat', 'محكمة الاستئناف سطات', TRUE),
('TR_APPL_7',  'Tribunal d''appel de Khouribga', 'محكمة الاستئناف - خريبكة', TRUE),
('TR_APPL_8',  'Tribunal d''appel de Casablanca', 'محكمة الاستئناف - الدار البيضاء', TRUE),
('TR_APPL_9',  'Tribunal d''appel de Marrakech', 'محكمة الاستئناف - مراكش', TRUE),
('TR_APPL_10', 'Tribunal d''appel de Safi', 'محكمة الاستئناف - آسفي', TRUE),
('TR_APPL_11', 'Tribunal d''appel de Tanger', 'محكمة الاستئناف - طنجة', TRUE),
('TR_APPL_12', 'Tribunal d''appel de Tetouan', 'محكمة الاستئناف - تطوان', TRUE),
('TR_APPL_13', 'Tribunal d''appel de Al Hoceima', 'محكمة الاستئناف - الحسيمة', TRUE),
('TR_APPL_14', 'Tribunal d''appel de Taza', 'محكمة الاستئناف - تازة', TRUE),
('TR_APPL_15', 'Tribunal d''appel de Oujda', 'محكمة الاستئناف - وجدة', TRUE),
('TR_APPL_16', 'Tribunal d''appel de Meknes', 'محكمة الاستئناف - مكناس', TRUE),
('TR_APPL_17', 'Tribunal d''appel de El Jadida', 'محكمة الاستئناف - الجديدة', TRUE),
('TR_APPL_18', 'Tribunal d''appel de Beni Mellal', 'محكمة الاستئناف - بني ملال', TRUE),
('TR_APPL_19', 'Tribunal d''appel de Errachidia', 'محكمة الاستئناف - الرشيدية', TRUE),
('TR_APPL_20', 'Tribunal d''appel de Nador', 'محكمة الاستئناف - الناظور', TRUE),
('TR_APPL_21', 'Tribunal d''appel de Fes', 'محكمة الاستئناف - فاس', TRUE),
('TR_APPL_22', 'Tribunal d''appel de Guelmim', 'محكمة الاستئناف - كلميم', TRUE),
('TR_PIN_1',  'Tribunal de 1ère instance de Rabat', 'المحكمة الابتدائية - الرباط', TRUE),
('TR_PIN_2',  'Tribunal de 1ère instance de Salé', 'المحكمة الابتدائية سلا', TRUE),
('TR_PIN_3',  'Tribunal de 1ère instance de Temara', 'المحكمة الابتدائية - تمارة', TRUE),
('TR_PIN_4',  'Tribunal de 1ère instance de Khemisset', 'المحكمة الابتدائية - الخميسات', TRUE),
('TR_PIN_5',  'Tribunal de 1ère instance de Rommani', 'المحكمة الابتدائية - الرماني', TRUE),
('TR_PIN_6',  'Tribunal de 1ère instance de Tiflet', 'المحكمة الابتدائية - تيفلت', TRUE),
('TR_PIN_7',  'Tribunal de 1ère instance de Oued Eddahab', 'المحكمة الابتدائية وادي الذهب', TRUE),
('TR_PIN_8',  'Tribunal de 1ère instance de Laayoune', 'المحكمة الابتدائية العيون', TRUE),
('TR_PIN_9',  'Tribunal de 1ère instance de Essmara', 'المحكمة الابتدائية السمارة', TRUE),
('TR_PIN_10', 'Tribunal de 1ère instance de Tata', 'المحكمة الابتدائية طاطا', TRUE),
('TR_PIN_11', 'Tribunal de 1ère instance de Inezgane', 'المحكمة الابتدائية إنزكان', TRUE),
('TR_PIN_12', 'Tribunal de 1ère instance de Biougra', 'المحكمة الابتدائية بيوكرى', TRUE),
('TR_PIN_13', 'Tribunal de 1ère instance de Taroudant', 'المحكمة الابتدائية تارودانت', TRUE),
('TR_PIN_14', 'Tribunal de 1ère instance de Tiznit', 'المحكمة الابتدائية تيزنيت', TRUE),
('TR_PIN_15', 'Tribunal de 1ère instance de Agadir', 'المحكمة الابتدائية أكادير', TRUE),
('TR_PIN_16', 'Tribunal de 1ère instance de Ouarzazate', 'المحكمة الابتدائية ورزازات', TRUE),
('TR_PIN_17', 'Tribunal de 1ère instance de Zagora', 'المحكمة الابتدائية زاكورة', TRUE),
('TR_PIN_18', 'Tribunal de 1ère instance de Tinghir', 'المحكمة الابتدائية تنغير', TRUE),
('TR_PIN_19', 'Tribunal de 1ère instance de Kenitra', 'المحكمة الابتدائية القنيطرة', TRUE),
('TR_PIN_20', 'Tribunal de 1ère instance de Sidi Slimane', 'المحكمة الابتدائية سيدي سليمان', TRUE),
('TR_PIN_21', 'Tribunal de 1ère instance de Souk El Arbaa', 'المحكمة الابتدائية سوق أربعاء الغرب', TRUE),
('TR_PIN_22', 'Tribunal de 1ère instance de Sidi Kacem', 'المحكمة الابتدائية سيدي قاسم', TRUE),
('TR_PIN_23', 'Tribunal de 1ère instance de Mechra Bel Ksiri', 'المحكمة الابتدائية مشرع بلقصيري', TRUE),
('TR_PIN_24', 'Tribunal de 1ère instance de Settat', 'المحكمة الابتدائية - سطات', TRUE),
('TR_PIN_25', 'Tribunal de 1ère instance de Berchid', 'المحكمة الابتدائية - برشيد', TRUE),
('TR_PIN_26', 'Tribunal de 1ère instance de Ben Ahmed', 'المحكمة الابتدائية - بن أحمد', TRUE),
('TR_PIN_27', 'Tribunal de 1ère instance de Khouribga', 'المحكمة الابتدائية - خريبكة', TRUE),
('TR_PIN_28', 'Tribunal de 1ère instance de Oued Zem', 'المحكمة الابتدائية - وادي زم', TRUE),
('TR_PIN_29', 'Tribunal de 1ère instance de Bejaad', 'المحكمة الابتدائية - أبي الجعد', TRUE),
('TR_PIN_30', 'Tribunal civile de Benslimane', 'المحكمة الابتدائية - بنسليمان', TRUE),
('TR_PIN_31', 'Tribunal de 1ère instance civile de Casablanca', 'المحكمة الابتدائية المدنية بالدار البيضاء', TRUE),
('TR_PIN_32', 'Tribunal de 1ère instance de Bouznika', 'المحكمة الابتدائية - بوزنيقة', TRUE),
('TR_PIN_33', 'Tribunal civile de Mohamedia', 'المحكمة الابتدائية - المحمدية', TRUE),
('TR_PIN_34', 'Tribunal correctionnel de Casablanca', 'المحكمة الابتدائية الزجرية الدار البيضاء', TRUE),
('TR_PIN_36', 'Tribunal de 1ère instance de Imintanout', 'المحكمة الابتدائية إيمنتانوت', TRUE),
('TR_PIN_37', 'Tribunal de 1ère instance de Marrakech', 'المحكمة الابتدائية - مراكش', TRUE),
('TR_PIN_38', 'Tribunal de 1ère instance de El Kelaa des Sraghna', 'المحكمة الابتدائية - قلعة السراغنة', TRUE),
('TR_PIN_39', 'Tribunal de 1ère instance de Ben Guerir', 'المحكمة الابتدائية - ابن جرير', TRUE),
('TR_PIN_40', 'Tribunal de 1ère instance de Tahanaout', 'المحكمة الابتدائية - تحناوت', TRUE),
('TR_PIN_41', 'Tribunal de 1ère instance de Essaouira', 'المحكمة الابتدائية - الصويرة', TRUE),
('TR_PIN_42', 'Tribunal de 1ère instance de Safi', 'المحكمة الابتدائية - آسفي', TRUE),
('TR_PIN_43', 'Tribunal de 1ère instance de Youssoufia', 'المحكمة الابتدائية - اليوسفية', TRUE),
('TR_PIN_44', 'Tribunal de 1ère instance de Tanger', 'المحكمة الابتدائية - طنجة', TRUE),
('TR_PIN_45', 'Tribunal de 1ère instance de Asilah', 'المحكمة الابتدائية - أصيلة', TRUE),
('TR_PIN_46', 'Tribunal de 1ère instance de Larache', 'المحكمة الابتدائية - العرائش', TRUE),
('TR_PIN_47', 'Tribunal de 1ère instance de Ksar El Kebir', 'المحكمة الابتدائية - القصر الكبير', TRUE),
('TR_PIN_48', 'Tribunal de 1ère instance de Ouazzane', 'المحكمة الابتدائية وزان', TRUE),
('TR_PIN_49', 'Tribunal de 1ère instance de Tetouan', 'المحكمة الابتدائية - تطوان', TRUE),
('TR_PIN_50', 'Tribunal de 1ère instance de Chefchaouen', 'المحكمة الابتدائية - شفشاون', TRUE),
('TR_PIN_51', 'Tribunal de 1ère instance de Mdiq', 'المحكمة الابتدائية - المضيق', TRUE),
('TR_PIN_52', 'Tribunal de 1ère instance de Al Hoceima', 'المحكمة الابتدائية - الحسيمة', TRUE),
('TR_PIN_53', 'Tribunal de 1ère instance de Targuist', 'المحكمة الابتدائية - تارجيست', TRUE),
('TR_PIN_54', 'Tribunal de 1ère instance de Taza', 'المحكمة الابتدائية - تازة', TRUE),
('TR_PIN_55', 'Tribunal de 1ère instance de Oujda', 'المحكمة الابتدائية - وجدة', TRUE),
('TR_PIN_56', 'Tribunal de 1ère instance de Berkane', 'المحكمة الابتدائية - بركان', TRUE),
('TR_PIN_57', 'Tribunal de 1ère instance de Guercif', 'المحكمة الابتدائية - جرسيف', TRUE),
('TR_PIN_58', 'Tribunal de 1ère instance de Taourirt', 'المحكمة الابتدائية - تاوريرت', TRUE),
('TR_PIN_59', 'Tribunal de 1ère instance de Jrada', 'المحكمة الابتدائية - جرادة', TRUE),
('TR_PIN_60', 'Tribunal de 1ère instance de Figuig Bouarfa', 'المحكمة الابتدائية - فجيج', TRUE),
('TR_PIN_61', 'Tribunal de 1ère instance de Meknes', 'المحكمة الابتدائية - مكناس', TRUE),
('TR_PIN_62', 'Tribunal de 1ère instance de Hajeb', 'المحكمة الابتدائية - الحاجب', TRUE),
('TR_PIN_63', 'Tribunal de 1ère instance de Azrou', 'المحكمة الابتدائية - آزرو', TRUE),
('TR_PIN_64', 'Tribunal de 1ère instance de El Jadida', 'المحكمة الابتدائية الجديدة', TRUE),
('TR_PIN_65', 'Tribunal de 1ère instance de Sidi Bennour', 'المحكمة الابتدائية سيدي بنور', TRUE),
('TR_PIN_66', 'Tribunal de 1ère instance de Beni Mellal', 'المحكمة الابتدائية - بني ملال', TRUE),
('TR_PIN_67', 'Tribunal de 1ère instance de Azilal', 'المحكمة الابتدائية - أزيلال', TRUE),
('TR_PIN_68', 'Tribunal de 1ère instance de Fquih Ben Salah', 'المحكمة الابتدائية - الفقيه بن صالح', TRUE),
('TR_PIN_69', 'Tribunal de 1ère instance de Khenifra', 'المحكمة الابتدائية - خنيفرة', TRUE),
('TR_PIN_70', 'Tribunal de 1ère instance de Kasba Tadla', 'المحكمة الابتدائية - قصبة تادلة', TRUE),
('TR_PIN_71', 'Tribunal de 1ère instance de Souk Sebt Oulad Nemma', 'المحكمة الابتدائية - سوق السبت أولاد النمة', TRUE),
('TR_PIN_72', 'Tribunal de 1ère instance de Errachidia', 'المحكمة الابتدائية - الرشيدية', TRUE),
('TR_PIN_73', 'Tribunal de 1ère instance de Midelt', 'المحكمة الابتدائية - ميدلت', TRUE),
('TR_PIN_74', 'Tribunal de 1ère instance de Nador', 'المحكمة الابتدائية - الناظور', TRUE),
('TR_PIN_75', 'Tribunal de 1ère instance de Driouch', 'المحكمة الابتدائية - الدريوش', TRUE),
('TR_PIN_76', 'Tribunal de 1ère instance de Fes', 'المحكمة الابتدائية - فاس', TRUE),
('TR_PIN_77', 'Tribunal de 1ère instance de Boulemane', 'المحكمة الابتدائية - بولمان', TRUE),
('TR_PIN_78', 'Tribunal de 1ère instance de Sefrou', 'المحكمة الابتدائية - صفرو', TRUE),
('TR_PIN_79', 'Tribunal de 1ère instance de Taouante', 'المحكمة الابتدائية - تاونات', TRUE),
('TR_PIN_80', 'Tribunal de 1ère instance de Guelmim', 'المحكمة الابتدائية كلميم', TRUE),
('TR_PIN_81', 'Tribunal de 1ère instance de Assa Zag', 'المحكمة الابتدائية أسا - الزاك', TRUE),
('TR_PIN_82', 'Tribunal de 1ère instance de Tantan', 'المحكمة الابتدائية طانطان', TRUE),
('TR_PIN_83', 'Tribunal de 1ère instance de Sidi Ifni', 'المحكمة الابتدائية سيدي إفني', TRUE),
('TR_CASS_1', 'Cour de cassation de Rabat', 'محكمة النقض بالرباط', TRUE)
) AS s (code, name_fr, name_ar, active)
ON t.code = s.code
WHEN MATCHED THEN UPDATE SET name_fr = s.name_fr, name_ar = s.name_ar, active = s.active
WHEN NOT MATCHED THEN INSERT (code, name_fr, name_ar, active) VALUES (s.code, s.name_fr, s.name_ar, s.active);
